const FETCH_MOVIE_START = "FETCH_MOVIE_START"
const FECTH_MOVIE_SUCCESS = "FECTH_MOVIE_SUCCESS"
const FETCH_MOVIE_FAILED = "FETCH_MOVIE_FAILED"

export {
    FETCH_MOVIE_START,
    FECTH_MOVIE_SUCCESS,
    FETCH_MOVIE_FAILED
}