const FETCH_SEARCH_START = "FETCH_SEARCH_START"
const FECTH_SEARCH_SUCCESS = "FECTH_SEARCH_SUCCESS"
const FETCH_SEARCH_FAILED = "FETCH_SEARCH_FAILED"

export {
    FETCH_SEARCH_START,
    FECTH_SEARCH_SUCCESS,
    FETCH_SEARCH_FAILED
}